import { create } from 'zustand';
import { sim,type Mode } from '../game/Simulation';
import { DEBUG_WEAPONS,EVOLUTION_LEVELS,xpThreshold,type DnaType,type UpgradeDefinition } from '../game/config';
import { runShootingDiagnostics,type ShootingDiagnostic } from '../game/shootingDiagnostics';
import { DEFAULT_AUDIO_SETTINGS,setAudioMode,setAudioSettings,startGameAudio,type AudioSettings } from '../effects/sound';
type Dna=Record<DnaType,number>;
type UI={mode:Mode;hp:number;maxHp:number;kills:number;time:number;alive:number;fps:number;calls:number;debug:boolean;shootingDebug:ShootingDiagnostic[]|null;progressionDebug:boolean;weaponDebug:boolean;audioSettings:AudioSettings;level:number;xp:number;xpNext:number;dna:Dna;weapon:string;upgradeChoices:UpgradeDefinition[];mutationName:string;evolutionFrom:string;publish:()=>void;start:()=>void;pause:()=>void;resume:()=>void;quit:()=>void;chooseUpgrade:(id:string)=>void;chooseMutation:(id:string)=>void;finishEvolution:()=>void;toggleDebug:()=>void;toggleShootingDebug:()=>void;toggleProgressionDebug:()=>void;toggleWeaponDebug:()=>void;setDebugWeapon:(slot:number)=>void;grantMutationTestXp:()=>void;setVolume:(key:keyof AudioSettings,value:number)=>void};
const snapshot=()=>({mode:sim.mode,hp:sim.player.hp,maxHp:sim.stats.maxHp,kills:sim.kills,time:sim.time,alive:sim.enemies.filter(e=>e.active&&e.hp>0).length,level:sim.level,xp:sim.xp,xpNext:sim.xpNext,dna:{...sim.dna},weapon:sim.weapon.name,upgradeChoices:sim.upgradeChoices,mutationName:sim.mutationName,evolutionFrom:sim.evolutionFrom});
export const useGameStore=create<UI>((set,get)=>({mode:'title',hp:100,maxHp:100,kills:0,time:0,alive:0,fps:0,calls:0,debug:false,shootingDebug:null,progressionDebug:false,weaponDebug:false,audioSettings:{...DEFAULT_AUDIO_SETTINGS},level:1,xp:0,xpNext:xpThreshold(1),dna:{volt:0,fire:0,cryo:0,mass:0},weapon:'SCRAP RIFLE',upgradeChoices:[],mutationName:'',evolutionFrom:'',
  publish:()=>set(snapshot()),start:()=>{sim.reset();startGameAudio();set(snapshot());},pause:()=>{sim.pause();setAudioMode('paused');set(snapshot());},resume:()=>{sim.resume();startGameAudio();set(snapshot());},quit:()=>{sim.reset();sim.mode='title';for(const e of sim.enemies)e.active=false;setAudioMode('title');set(snapshot());},chooseUpgrade:id=>{sim.chooseUpgrade(id);setAudioMode(sim.mode);set(snapshot());},chooseMutation:id=>{sim.chooseMutation(id);setAudioMode(sim.mode);set(snapshot());},finishEvolution:()=>{sim.finishEvolution();setAudioMode(sim.mode);set(snapshot());},toggleDebug:()=>set(s=>({debug:!s.debug})),toggleShootingDebug:()=>{if(import.meta.env.DEV)set(s=>({shootingDebug:s.shootingDebug?null:runShootingDiagnostics()}));},toggleProgressionDebug:()=>{if(import.meta.env.DEV)set(s=>({progressionDebug:!s.progressionDebug}));},toggleWeaponDebug:()=>{if(import.meta.env.DEV)set(s=>({weaponDebug:!s.weaponDebug}));},setDebugWeapon:slot=>{if(!import.meta.env.DEV||!get().weaponDebug||!['playing','paused'].includes(sim.mode))return;const weapon=DEBUG_WEAPONS[slot];if(!weapon)return;sim.equipDebugWeapon(weapon);set(snapshot());},grantMutationTestXp:()=>{if(!import.meta.env.DEV||sim.mode!=='playing')return;const target=EVOLUTION_LEVELS.find(level=>level>sim.level);if(!target)return;let amount=sim.xpNext-sim.xp;for(let level=sim.level+1;level<target;level++)amount+=xpThreshold(level);sim.gainXp(amount);setAudioMode(sim.mode);set(snapshot());},setVolume:(key,value)=>{const next={...get().audioSettings,[key]:Math.max(0,Math.min(1,value))};setAudioSettings(next);set({audioSettings:next});}}));
