import { useEffect,useRef } from 'react';
import { useProgress } from '@react-three/drei';
import { useGameStore } from '../stores/gameStore';
import { sim } from '../game/Simulation';
import { CONFIG,MUTATIONS } from '../game/config';
import { getAudioDebug } from '../effects/sound';
const clock=(n:number)=>`${Math.floor(n/60).toString().padStart(2,'0')}:${Math.floor(n%60).toString().padStart(2,'0')}`;
const mutationCopy:Record<string,{tag:string;body:string;cost:string}>={thunderstorm:{tag:'VOLT / CROWD',body:'Rapid multi-barrel fire chains lightning through nearby infected.',cost:'VOLT DNA SYNCHRONIZED'},hellbreaker:{tag:'FIRE / IMPACT',body:'Five explosive pellets ignite clusters at close and mid range.',cost:'FIRE DNA SYNCHRONIZED'},'absolute-zero':{tag:'CRYO / CONTROL',body:'Precision rail shots pierce lines and freeze every infected struck.',cost:'CRYO DNA SYNCHRONIZED'}};
export function Interface(){const s=useGameStore();const loading=useProgress();const crosshair=useRef<HTMLDivElement>(null);
  useEffect(()=>{const move=(e:PointerEvent)=>{if(crosshair.current)crosshair.current.style.transform=`translate(${e.clientX}px,${e.clientY}px)`;if(e.target instanceof HTMLCanvasElement)sim.input.aiming=true;};window.addEventListener('pointermove',move);return()=>window.removeEventListener('pointermove',move);},[]);
  useEffect(()=>{if(s.mode!=='evolving')return;const timer=setTimeout(()=>useGameStore.getState().finishEvolution(),2100);return()=>clearTimeout(timer);},[s.mode]);
  const element=s.weapon==='THUNDERSTORM'?'VOLT':s.weapon==='HELLBREAKER'?'FIRE':s.weapon==='ABSOLUTE ZERO'?'CRYO':'KINETIC';
  return <><div className="grain"/>
    {s.mode!=='title'&&<><div key={s.hp} className={`damage-edges ${s.hp<s.maxHp?'hit-flash':''}`} style={{animationPlayState:s.mode==='paused'?'paused':'running'}}/><div className={`low-health ${s.hp/s.maxHp<=.28?'critical':''}`}/><div key={sim.player.generation} className="run-transition"/></>}
    {s.mode!=='title'&&<div className="hud"><section className="health"><div className="eyebrow"><span className="status-dot"/> SURVIVOR 01 <span className="hp-label">HP / {s.hp}</span></div><div className="health-track"><div style={{width:`${s.hp/s.maxHp*100}%`,background:s.hp/s.maxHp<.3?'#fc654c':undefined}}/></div><small>{s.hp/s.maxHp<.3?'CRITICAL CONDITION':`ARMOR ${Math.round(sim.stats.armor*100)}%`}</small><div className="dna-strip"><span className="volt">V {s.dna.volt}</span><span className="fire">F {s.dna.fire}</span><span className="cryo">C {s.dna.cryo}</span><span className="mass">M {s.dna.mass}</span></div></section><section className="kill-counter"><span className="eyebrow">INFECTED ELIMINATED</span><strong>{String(s.kills).padStart(3,'0')}</strong></section><section className="level-meter"><div><span>LEVEL {String(s.level).padStart(2,'0')}</span><b>{s.xp} / {s.xpNext} BIO-ENERGY</b></div><div className="xp-track"><i style={{width:`${Math.min(100,s.xp/s.xpNext*100)}%`}}/></div></section><div className="sector"><span>QUARANTINE ZONE 04</span><b>{clock(s.time)}</b></div><section className={`weapon ${element.toLowerCase()}`}><svg className="rifle-icon" viewBox="0 0 100 36"><path d="M3 12h16v4h10V9h33v5h30v5H61v5H45l-4 10H31l4-12H19l-10 5H3z" fill="currentColor"/><path d="M38 5h18v4H38zM91 12h6v10h-6z" fill="currentColor"/></svg><div><span className="eyebrow">EVOLUTION {sim.weapon.evolutionStage} / {element}</span><strong>{s.weapon}</strong></div><span className="weapon-state">● READY</span></section><div className="controls">W A S D <span>MOVE</span> / MOUSE <span>AIM</span> / LMB <span>FIRE</span> / ESC <span>PAUSE</span></div><button className="pause-button" onClick={s.pause}>Ⅱ</button></div>}
    {s.mode==='playing'&&<div ref={crosshair} className="crosshair"><i/><i/></div>}
    {s.mode==='title'&&<div className="title-screen"><header><span className="brand-small">DS<span>//</span> RESEARCH DIVISION</span><span className="build-tag">ZONE 04 / LAST LIGHT</span></header><main><div className="eyebrow"><span className="status-dot"/> CONTAINMENT HAS FAILED</div><h1>DEAD<span>//</span><br/>SHIFT</h1><div className="subtitle">M U T A T I O N &nbsp; R U N</div><p>The city is gone.<br/>Evolve before it takes you.</p><button className="primary" disabled={loading.active} onClick={s.start}>{loading.active?`PREPARING ZONE · ${Math.round(loading.progress)}%`:'START RUN'} <span>↗</span></button><div className="title-controls"><span>WASD <b>MOVE</b></span><span>MOUSE <b>AIM + FIRE</b></span><span>ESC <b>PAUSE</b></span></div></main><footer><span>HARVEST. MUTATE. SURVIVE.</span><span>DEAD//SHIFT © 2026</span></footer></div>}
    {s.mode==='levelup'&&<div className="choice-backdrop"><section className="choice-panel"><span className="eyebrow">BIO-SYNAPTIC RESPONSE DETECTED</span><h2>LEVEL {s.level} <em>// SELECT ADAPTATION</em></h2><div className="upgrade-grid">{s.upgradeChoices.map((u,i)=><button key={u.id} className="upgrade-card" onClick={()=>s.chooseUpgrade(u.id)}><span className="card-index">0{i+1} / {u.rarity}</span><i>{u.icon}</i><strong>{u.name}</strong><p>{u.description}</p><b>INSTALL →</b></button>)}</div><small>COMBAT SIMULATION SUSPENDED</small></section></div>}
    {s.mode==='mutation'&&<div className="choice-backdrop mutation-backdrop"><section className="choice-panel"><span className="eyebrow">WEAPON MUTATION AVAILABLE</span><h2>WEAPON MUTATION <em>// CHOOSE A BRANCH</em></h2><div className="upgrade-grid mutation-grid">{MUTATIONS.map((w,i)=><button key={w.id} className={`upgrade-card mutation-card ${w.element}`} onClick={()=>s.chooseMutation(w.id)}><span className="card-index">0{i+1} / {mutationCopy[w.id].tag}</span><div className="mutation-glyph">{w.element==='volt'?'ϟ':w.element==='fire'?'▲':'❄'}</div><strong>{w.name}</strong><p>{mutationCopy[w.id].body}</p><small>{mutationCopy[w.id].cost}</small><b>EVOLVE →</b></button>)}</div><small>ONE BRANCH. NO REVERSAL THIS RUN.</small></section></div>}
    {s.mode==='evolving'&&<div className={`evolution-screen ${element.toLowerCase()}`}><span>SCRAP RIFLE</span><i>↓</i><div className="evolution-core"/><h2>{s.mutationName}</h2><b>EVOLUTION COMPLETE</b></div>}
    {(s.mode==='paused'||s.mode==='dead')&&<div className="modal-backdrop"><section className="menu" role="dialog" aria-modal="true"><span className="eyebrow">DEAD//SHIFT · MUTATION RUN</span><h2>{s.mode==='dead'?'YOU DIED':'PAUSED'}</h2><p>{s.mode==='dead'?'The quarantine claimed another survivor.':'Combat simulation suspended.'}</p><div className="run-stats"><span><b>{clock(s.time)}</b> SURVIVED</span><span><b>{s.kills}</b> ELIMINATED</span><span><b>{s.level}</b> LEVEL</span></div>{s.mode==='paused'&&<div className="audio-controls">{(['master','music','sfx'] as const).map(key=><label key={key}><span>{key.toUpperCase()} <b>{Math.round(s.audioSettings[key]*100)}%</b></span><input aria-label={`${key} volume`} type="range" min="0" max="100" value={Math.round(s.audioSettings[key]*100)} onChange={e=>s.setVolume(key,Number(e.target.value)/100)}/></label>)}</div>}{s.mode==='paused'&&<button autoFocus className="primary" onClick={s.resume}>RESUME <span>→</span></button>}<button autoFocus={s.mode==='dead'} className={s.mode==='dead'?'primary':'secondary'} onClick={s.start}>RESTART RUN <span>↻</span></button><button className="text-button" onClick={s.quit}>QUIT TO TITLE</button></section></div>}
    {s.debug&&<aside className="performance"><b>FIELD TELEMETRY / F3</b><span>FPS <strong>{s.fps}</strong></span><span>Enemies <strong>{s.alive}</strong></span><span>Draw Calls <strong>{s.calls}</strong></span><span>Pickups <strong>{sim.pickups.filter(p=>p.active).length}</strong></span><span>Position <strong>{sim.player.x.toFixed(1)}, {sim.player.z.toFixed(1)}</strong></span></aside>}
    {import.meta.env.DEV&&s.shootingDebug&&<aside style={{position:'absolute',right:20,top:110,zIndex:30,padding:14,background:'#071116ee',color:'#eff7ef',font:'12px monospace',lineHeight:1.65,border:'1px solid #6ee7aa'}}><b>F5 / CLOSE-RANGE RIFLE TEST</b>{s.shootingDebug.map(r=><div key={r.distance}>{r.distance.toFixed(2)}m · {r.hit?'HIT':'MISS'} · origin ({r.origin.map(n=>n.toFixed(2)).join(', ')}) · impact ({r.hitPoint.map(n=>n.toFixed(2)).join(', ')})</div>)}<div>Live shots: {sim.shots} · last ray: {sim.lastRay?sim.lastRay.hit?'HIT':sim.lastRay.blocked?'BLOCKED':'MISS':'—'}</div></aside>}
    {import.meta.env.DEV&&s.progressionDebug&&<aside className="progression-debug"><b>F6 / PROGRESSION</b><span>Level {s.level}</span><span>XP {s.xp} / {s.xpNext}</span><span>XP to next {Math.max(0,s.xpNext-s.xp)}</span><span>Damage {(sim.weapon.damage*sim.stats.damage).toFixed(1)}</span><span>Fire rate {(sim.weapon.fireRate*sim.stats.fireRate).toFixed(2)} /s</span><span>Movement {(CONFIG.playerSpeed*sim.stats.movement).toFixed(2)} m/s</span><span>Max HP {sim.stats.maxHp}</span><span>Armor {(sim.stats.armor*100).toFixed(0)}%</span><span>Crit chance {(sim.stats.critChance*100).toFixed(0)}%</span><span>Pickup radius {sim.stats.pickupRadius.toFixed(2)} m</span><span>Shot range {(sim.weapon.range*sim.stats.range).toFixed(1)} m</span><span>Music {getAudioDebug().musicLoaded?'loaded':'loading'} / {getAudioDebug().state}</span><span>Threat {(getAudioDebug().threat*100).toFixed(0)}%</span>{s.mode==='playing'&&s.level<CONFIG.mutationLevel&&<button type="button" onClick={s.grantMutationTestXp}>Test level 5 flow</button>}</aside>}
    {import.meta.env.DEV&&s.weaponDebug&&<aside className="weapon-debug"><b>F7 / WEAPON TEST</b><span>1 Scrap Rifle · 2 Thunderstorm</span><span>3 Hellbreaker · 4 Absolute Zero</span><strong>{s.weapon}</strong></aside>}
  </>;
}
