export type LabId = 'states' | 'materials' | 'separation' | 'indicators' | 'changes' | 'metals' | 'solutions' | 'atoms' | 'molecules';
export type Lab = { id: LabId; title: string; subtitle: string; grades: number[]; tag: string; question: string; concept: string; everyday: string; tryIt: string; limitation: string; quiz: { prompt: string; options: string[]; answer: number; explanation: string } };
export const labs: Lab[] = [
 {id:'states',title:'The particle playground',subtitle:'One substance. Three very different worlds.',grades:[6,8],tag:'States of matter',question:'What changes when ice becomes water?',concept:'Matter is made of tiny particles. In a solid, particles vibrate around fixed positions. In a liquid, they stay close but move past each other. In a gas, particles move freely with much larger gaps. A change of state does not make a new substance.',everyday:'Water vapour cools on a cold steel tumbler and condenses into liquid droplets. The water comes from the surrounding air.',tryIt:'Compare solid and gas. Do the particles themselves become bigger, or do the gaps change?',limitation:'Schematic particle model: particle sizes, spacing and speeds are exaggerated. The motion slider is not a thermometer. Water has extra structural details not shown here.',quiz:{prompt:'When liquid water becomes water vapour, what happens to its particles?',options:['They become much larger','They move farther apart','They turn into air particles'],answer:1,explanation:'Water remains water. In the gas state its particles are much farther apart; the particles do not expand to fill the container.'}},
 {id:'materials',title:'Meet the materials',subtitle:'Look beyond the surface.',grades:[6],tag:'Material properties',question:'Why is a window made of glass rather than wood?',concept:'We choose materials for their properties. Transparent materials let us see clearly through them; translucent ones transmit light but blur details; opaque ones do not let us see through. Solubility, hardness and lustre are other useful properties.',everyday:'A steel saucepan is strong and conducts heat. Its wooden handle is a poorer conductor and is easier to hold.',tryIt:'Switch materials. Find one that lets you see the pattern clearly, one that blurs it, and one that blocks it.',limitation:'The samples represent typical classroom examples. Thickness, coatings and surface finish can change how a real material behaves.',quiz:{prompt:'Which material lets light through but blurs the view?',options:['Transparent','Translucent','Opaque'],answer:1,explanation:'A translucent material, such as frosted glass, scatters light. You can detect light through it without seeing a clear image.'}},
 {id:'separation',title:'Separate the mixture',subtitle:'Choose a method. Discover what stays behind.',grades:[6,9],tag:'Separation',question:'Can filter paper remove salt dissolved in water?',concept:'Separation uses differences in physical properties. Filter paper traps insoluble sand but lets dissolved salt pass with water. Evaporation removes the water and leaves salt behind. A magnet attracts iron filings but not sand.',everyday:'A kitchen strainer catches tea leaves. It does not remove sugar that has dissolved in the tea.',tryIt:'Try filtering salt water, then choose evaporation. Explain why the two outcomes differ.',limitation:'A simplified before-and-after model, not a timed experiment. Evaporation here does not collect the water; distillation would. Never drink water simply because it looks clear.',quiz:{prompt:'How can you recover salt from salt water in this lab?',options:['Filter it through paper','Use a magnet','Evaporate the water'],answer:2,explanation:'Dissolved salt passes through ordinary filter paper. When the water evaporates, the salt remains.'}},
 {id:'indicators',title:'The colour detective',subtitle:'Let litmus reveal the clue.',grades:[7],tag:'Acids & bases',question:'Can colour tell you whether a solution is acidic?',concept:'Indicators help classify solutions without tasting them. An acid turns blue litmus red. A base turns red litmus blue. A neutral solution does not change either colour. Litmus does not measure the exact strength of an acid or base.',everyday:'Lemon juice contains citric acid. A soap solution is usually basic. Indicators help us compare their chemical nature safely.',tryIt:'Test both colours of litmus in lemon juice, soap solution and neutral water. Look for the strip that changes.',limitation:'These are typical sample classifications, not precise measurements of household products. No tasting or mixing real household chemicals; this is a virtual test.',quiz:{prompt:'Blue litmus becomes red. What does that show?',options:['The solution is acidic','The solution is basic','The solution is always safe to touch'],answer:0,explanation:'Acids turn blue litmus red. Indicator colour does not establish whether a substance is safe.'}},
 {id:'changes',title:'Change, or a new substance?',subtitle:'Look for evidence, not just appearances.',grades:[7],tag:'Physical & chemical changes',question:'Are all irreversible changes chemical changes?',concept:'A physical change alters form or state without making a new substance. A chemical change makes new substances. Reversibility is a useful clue, but not a definition: tearing paper is hard to reverse and is still a physical change.',everyday:'Melting ice is physical. Rusting an iron gate is chemical: iron reacts with oxygen and water to form rust.',tryIt:'Compare melting ice, tearing paper and rusting iron. Which example forms a new substance?',limitation:'Time is compressed. Rusting normally takes much longer than the animation. A colour change alone is not proof of a chemical reaction.',quiz:{prompt:'Tearing paper is difficult to reverse. It is…',options:['Chemical, because it is irreversible','Physical, because no new substance forms','Neither physical nor chemical'],answer:1,explanation:'The pieces are still paper. Making a new substance, not reversibility alone, distinguishes a chemical change.'}},
 {id:'metals',title:'Materials in a circuit',subtitle:'Which sample completes the path?',grades:[8],tag:'Metals & non-metals',question:'Do only metals conduct electricity?',concept:'Most metals conduct electricity well. Many non-metals are poor conductors, but graphite, a form of carbon, is an important exception. One property alone is not enough to identify a material as a metal.',everyday:'Copper carries current inside a wire. The plastic coating helps insulate you from the conductor.',tryIt:'Complete the low-voltage model circuit with copper, plastic and graphite. Find the exception to the usual rule.',limitation:'A qualitative circuit: equal lamp brightness means “conducts” here, not equal conductivity. Only virtual samples are used. Never experiment with a mains socket.',quiz:{prompt:'Which non-metal can conduct electricity?',options:['Plastic','Graphite','Dry wood'],answer:1,explanation:'Graphite conducts electricity even though carbon is a non-metal. It is an exception to the usual classroom generalisation.'}},
 {id:'solutions',title:'Mix, measure, compare',subtitle:'Make concentration make sense.',grades:[9],tag:'Mixtures & solutions',question:'Is 10 g of salt in 100 g of water a 10% solution?',concept:'For mass-by-mass concentration, divide the mass of dissolved solute by the total mass of the solution, then multiply by 100. The denominator includes both solute and solvent. Adding water lowers the concentration without removing solute.',everyday:'Two glasses can contain the same amount of sugar but taste different if one contains more water.',tryIt:'Set solute to 10 g and water to 100 g. Then double only the water. What happens to the mass percentage?',limitation:'Assumes all the salt dissolves, no evaporation and room-temperature water. The sliders stay below a typical salt saturation limit. This is mass percentage, not mass per volume.',quiz:{prompt:'10 g salt dissolves in 90 g water. What is its mass percentage?',options:['10%','11.1%','90%'],answer:0,explanation:'Solution mass = 10 + 90 = 100 g. Mass percentage = (10 ÷ 100) × 100 = 10%.'}},
 {id:'atoms',title:'Inside the atom',subtitle:'Small particles. A big identity.',grades:[9],tag:'Atomic structure',question:'Which particle decides the identity of an element?',concept:'Protons have positive charge, electrons negative charge, and neutrons no charge. Atomic number equals the number of protons. A neutral atom has equal numbers of protons and electrons. Mass number counts protons plus neutrons.',everyday:'Carbon-12 and carbon-14 are isotopes. Both have six protons, but they have different numbers of neutrons.',tryIt:'Choose oxygen, then sodium. Compare the number of protons and the distribution of electrons between shells.',limitation:'A simplified Bohr shell model for selected neutral atoms, not literal electron paths. Nucleus size and distances are not to scale. One isotope is shown for each element.',quiz:{prompt:'An atom has 8 protons and 10 neutrons. Its atomic number is…',options:['18','10','8'],answer:2,explanation:'Atomic number counts protons only: 8. Its mass number is 8 + 10 = 18.'}},
 {id:'molecules',title:'Build a molecular picture',subtitle:'Read the formula. Count the atoms.',grades:[9],tag:'Atoms & molecules',question:'What does the little 2 in H₂O tell you?',concept:'A molecular formula tells us the types and numbers of atoms in one molecule. H₂O has two hydrogen atoms and one oxygen atom. O₂ is a molecule of an element; H₂O is a molecule of a compound. Molecular mass is the sum of the atomic masses.',everyday:'Water, oxygen and carbon dioxide all contain oxygen atoms, but their different combinations give them different properties.',tryIt:'Switch between H₂O, O₂ and CO₂. Count each colour and check the molecular mass.',limitation:'Ball-and-stick representations use conventional colours. Atoms are not actually coloured balls. Sizes and bonds are schematic; ionic solids such as salt are not shown as isolated molecules.',quiz:{prompt:'Using H = 1 u and O = 16 u, what is the molecular mass of H₂O?',options:['17 u','18 u','32 u'],answer:1,explanation:'Two hydrogen atoms and one oxygen atom give 2 × 1 + 16 = 18 u.'}},
];
export const atoms = [
 {name:'Hydrogen',symbol:'H',protons:1,neutrons:0,shells:[1]},
 {name:'Carbon',symbol:'C',protons:6,neutrons:6,shells:[2,4]},
 {name:'Oxygen',symbol:'O',protons:8,neutrons:8,shells:[2,6]},
 {name:'Sodium',symbol:'Na',protons:11,neutrons:12,shells:[2,8,1]},
 {name:'Chlorine',symbol:'Cl',protons:17,neutrons:18,shells:[2,8,7]},
];
export const molecules = [
 {formula:'H₂O',name:'Water',composition:'2 hydrogen + 1 oxygen',mass:18,expression:'2 × 1 + 16',compound:true,atoms:[{el:'O',p:[0,0,0]},{el:'H',p:[-1.05,-.8,0]},{el:'H',p:[1.05,-.8,0]}]},
 {formula:'O₂',name:'Oxygen',composition:'2 oxygen',mass:32,expression:'2 × 16',compound:false,atoms:[{el:'O',p:[-.65,0,0]},{el:'O',p:[.65,0,0]}]},
 {formula:'CO₂',name:'Carbon dioxide',composition:'1 carbon + 2 oxygen',mass:44,expression:'12 + 2 × 16',compound:true,atoms:[{el:'C',p:[0,0,0]},{el:'O',p:[-1.5,0,0]},{el:'O',p:[1.5,0,0]}]},
];
export function concentration(solute: number, water: number) { return solute / (solute + water) * 100; }
export function litmus(sample: number, strip: number) { return sample===0 ? 'red' : sample===1 ? 'blue' : strip===0 ? 'blue' : 'red'; }
export function separationResult(mixture: number, method: number) {
 if(mixture===0&&method===0)return {works:true,result:'Sand stays in the filter. Water passes through.',residue:'Sand',collected:'Water'};
 if(mixture===1&&method===1)return {works:true,result:'Water escapes as vapour. Salt remains in the dish.',residue:'Salt',collected:'Water vapour (not collected)'};
 if(mixture===2&&method===2)return {works:true,result:'Iron filings follow the magnet. Sand stays behind.',residue:'Sand',collected:'Iron filings'};
 if(mixture===1&&method===0)return {works:false,result:'The salt passes through with the water. The filtrate is still salt water.',residue:'No salt trapped',collected:'Salt water'};
 if(mixture===0&&method===1)return {works:true,result:'Water evaporates and leaves sand. Filtration would recover the liquid water too.',residue:'Sand',collected:'Water vapour (not collected)'};
 return {works:false,result:'This method does not separate this mixture in our model. Choose a property that differs between its components.',residue:'Mixture unchanged',collected:'Nothing separated'};
}
