import { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Atom, BookOpen, CheckCircle2, FlaskConical, Sparkles } from "lucide-react";

export const metadata: Metadata = { title: "Interactive Education Labs | Nabendu", description: "Explore interactive Physics and Chemistry learning labs for CBSE Classes 6–9." };

const LABS = [
  { title: "Physics", eyebrow: "MECHANICA LAB", emoji: "⚛️", icon: Atom, description: "Build intuition for forces, energy and simple machines with movable 3D mechanisms and live force vectors.", features: ["Interactive simple machines and mechanisms", "Live force vectors and measurements", "Lessons for CBSE Classes 6–9"], tags: ["3D Models", "Forces & Energy", "Simple Machines"], href: "/education/physics", card: "bg-gradient-to-b from-sky-50 via-white to-sky-50/40 dark:from-sky-950/40 dark:via-slate-900/70 dark:to-slate-950/90 border-sky-200/80 dark:border-sky-500/25 hover:border-sky-400 dark:hover:border-sky-500/60", badge: "bg-sky-100 text-sky-800 border-sky-300/80 dark:bg-sky-500/15 dark:text-sky-300 dark:border-sky-500/30", iconColor: "text-sky-600 dark:text-sky-400", tag: "bg-sky-100/70 text-sky-900 border-sky-200/70 dark:bg-white/5 dark:text-sky-200 dark:border-white/10", button: "bg-sky-600 hover:bg-sky-500 shadow-sky-700/20 dark:shadow-sky-950/50" },
  { title: "Chemistry", eyebrow: "ELEMENTA LAB", emoji: "🧪", icon: FlaskConical, description: "Move through particles, mixtures, atoms and molecules with a virtual lab where every experiment is hands-on and visual.", features: ["Nine interactive experiments for Classes 6–9", "Move glassware, atoms and molecules in 3D", "Quizzes and a personal lab notebook"], tags: ["3D Workbench", "Matter & Mixtures", "Atoms & Molecules"], href: "/education/chemistry", card: "bg-gradient-to-b from-lime-50 via-white to-violet-50/40 dark:from-lime-950/35 dark:via-slate-900/70 dark:to-violet-950/30 border-lime-200/80 dark:border-lime-500/25 hover:border-lime-400 dark:hover:border-lime-500/60", badge: "bg-lime-100 text-lime-800 border-lime-300/80 dark:bg-lime-500/15 dark:text-lime-300 dark:border-lime-500/30", iconColor: "text-lime-700 dark:text-lime-400", tag: "bg-lime-100/70 text-lime-900 border-lime-200/70 dark:bg-white/5 dark:text-lime-200 dark:border-white/10", button: "bg-lime-700 hover:bg-lime-600 shadow-lime-700/20 dark:shadow-lime-950/50" },
];

export default function EducationPage() {
  return <div className="container max-w-6xl space-y-12 py-10 lg:py-16">
    <section className="relative overflow-hidden rounded-3xl border border-border/50 bg-gradient-to-r from-neutral-900 via-slate-800 to-neutral-900 p-8 text-white shadow-2xl dark:from-neutral-950 dark:via-slate-900 dark:to-neutral-950 md:p-12"><div aria-hidden="true" className="absolute inset-0 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px] [mask-image:radial-gradient(ellipse_70%_80%_at_50%_0%,#000_70%,transparent_100%)]" /><div className="relative z-10 max-w-3xl space-y-4"><div className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/20 px-3.5 py-1 text-xs font-semibold text-primary-foreground backdrop-blur-md"><BookOpen className="h-4 w-4 text-primary" /> Interactive Education Labs</div><h1 className="text-4xl font-black tracking-tight md:text-5xl lg:text-6xl">Learn by exploring. <span className="text-sky-300">🔬</span></h1><p className="text-base leading-relaxed text-neutral-300 md:text-lg">Interactive science experiences for CBSE Classes 6–9. Turn concepts into something you can see, change and understand.</p></div></section>
    <section className="grid grid-cols-1 gap-8 lg:grid-cols-2" aria-label="Education labs">{LABS.map((lab) => { const Icon = lab.icon; return <article key={lab.title} className={`group relative flex flex-col justify-between overflow-hidden rounded-2xl border p-6 shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-xl dark:shadow-xl sm:p-8 ${lab.card}`}><div className="space-y-6"><div className="flex items-start justify-between gap-4"><div className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-semibold ${lab.badge}`}><Icon className={`h-4 w-4 ${lab.iconColor}`} /> {lab.eyebrow}</div><span className="text-3xl" aria-hidden="true">{lab.emoji}</span></div><div><h2 className="text-3xl font-bold tracking-tight text-slate-900 dark:text-slate-100">{lab.title}</h2><p className="mt-3 text-sm leading-relaxed text-slate-700 dark:text-slate-300 sm:text-base">{lab.description}</p></div><div className="space-y-2.5 rounded-xl border border-slate-200/70 bg-white/60 p-4 backdrop-blur-sm dark:border-white/10 dark:bg-black/30"><p className="text-xs font-semibold uppercase tracking-wider text-slate-600 dark:text-slate-300">What you can explore</p>{lab.features.map((feature) => <div key={feature} className="flex items-center gap-2.5 text-xs font-medium text-slate-800 dark:text-slate-200 sm:text-sm"><CheckCircle2 className={`h-4 w-4 shrink-0 ${lab.iconColor}`} />{feature}</div>)}</div><div className="flex flex-wrap gap-1.5">{lab.tags.map((tag) => <span key={tag} className={`rounded-md border px-2.5 py-1 text-[11px] font-medium ${lab.tag}`}>{tag}</span>)}</div></div><div className="mt-6 border-t border-slate-200 pt-6 dark:border-white/10"><Link href={lab.href} className={`inline-flex w-full items-center justify-center gap-2 rounded-xl px-5 py-3 text-sm font-semibold text-white transition-all duration-200 group-hover:gap-3 ${lab.button}`}>Open {lab.title} Lab <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></Link></div></article>; })}</section>
    <section className="rounded-2xl border border-dashed border-border bg-card/60 p-6 text-center shadow-sm backdrop-blur-sm dark:bg-card/40 sm:p-8"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full border border-primary/20 bg-primary/10"><Sparkles className="h-6 w-6 text-primary" /></div><h2 className="mt-4 text-lg font-bold text-slate-900 dark:text-slate-100 sm:text-xl">Built for curiosity</h2><p className="mx-auto mt-2 max-w-xl text-sm text-slate-600 dark:text-muted-foreground">Choose a lab, change the controls, and make your own observations. Every experience is designed to complement classroom learning.</p></section>
  </div>;
}
