import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
function glb(path:string){const b=fs.readFileSync(new URL('../public/assets/'+path+'.glb',import.meta.url));assert.equal(b.readUInt32LE(0),0x46546c67);assert.equal(b.readUInt32LE(8),b.length);return JSON.parse(b.subarray(20,20+b.readUInt32LE(12)).toString());}
test('Blender character family has skins and class-specific animation sets',()=>{for(const [path,clips] of [['characters/survivor',['Idle','Run','Aim','Shoot','Hit','Death']],['zombies/walker',['Idle','Walk','Attack','Hit','Death']],['zombies/runner',['Idle','Run','Attack','Hit','Death']],['zombies/tank',['Idle','Heavy Walk','Heavy Attack','Hit','Death']],['zombies/hazmat',['Idle','Walk','Attack','Hit','Death']]] as [string,string[]][]){const data=glb(path);assert.ok(data.skins.length>0,path);assert.ok(data.meshes.length>0,path);for(const clip of clips)assert.ok(data.animations.some((a:{name:string;channels:unknown[]})=>a.name===clip&&a.channels.length>0),`${path}:${clip}`);}});
test('modular rifle attachment nodes and muzzle survive GLB export',()=>{const data=glb('weapons/scrap-rifle');for(const node of ['BARREL','CORE','MAGAZINE','UNDERBARREL','SIDE_MODULE','Muzzle'])assert.ok(data.nodes.some((n:{name:string})=>n.name===node));});
test('all arena props are valid, self-contained GLBs',()=>{for(const name of ['intersection','shop','abandoned-car','barrier','dumpster','streetlight','debris']){const data=glb('environment/'+name);assert.ok(data.meshes.length>0);assert.ok(data.buffers.every((b:{uri?:string})=>!b.uri));assert.ok((data.images??[]).every((i:{uri?:string})=>!i.uri));}});
test('ruined city kit exports contain geometry without unrelated scene objects',()=>{for(const name of ['apartment','broken-shop','corner-ruin','petrol-station','burned-car','police-car','ambulance','collapsed-wall','sandbags','fence','road-sign','checkpoint','trash','rubble','asphalt-chunks','oil-stain','blood-stain','pothole','city-skirt']){const data=glb('environment/'+name);assert.equal(data.meshes.length,1,name);assert.ok(data.meshes[0].primitives.length>0,name);assert.ok(data.buffers.every((b:{uri?:string})=>!b.uri),name);}});
test('each weapon mutation is a named, self-contained Blender mesh',()=>{for(const name of ['thunderstorm','hellbreaker','absolute-zero']){const data=glb('weapons/'+name);assert.equal(data.meshes.length,1,name);assert.ok(data.meshes[0].primitives.length>=4,name);assert.ok(data.buffers.every((b:{uri?:string})=>!b.uri),name);assert.ok(data.nodes.some((n:{name?:string})=>n.name?.toLowerCase().replaceAll('-','').includes(name.replaceAll('-',''))),name);}});
