import { test } from 'node:test';
import assert from 'node:assert/strict';
import { Simulation } from '../src/game/Simulation';
import { ANTI_MATERIEL, BATTLE_DMR, BREACHER, CONFIG, DEBUG_WEAPONS, EVOLUTION_LEVELS, HEAVY_GUNNER, HELLMAKER, M249_SUPPORT, RPK, SAIGA_12, SURVIVOR_AK, UPGRADES, WEAPON_EVOLUTIONS, xpThreshold } from '../src/game/config';
function fresh(){const s=new Simulation();s.reset();for(const e of s.enemies)e.active=false;s.stats.critChance=0;return s;}
function advance(s:Simulation,seconds:number){for(let n=0;n<seconds*60;n++)s.step(1/60);}
function upgrade(s:Simulation,id:string){const card=UPGRADES.find(u=>u.id===id)!;card.apply(s.stats,amount=>{s.player.hp=Math.min(s.stats.maxHp,s.player.hp+amount);});}
test('level thresholds',()=>assert.deepEqual([1,2,3,4,5].map(level=>xpThreshold(level)),[36,54,72,90,108]));
test('XP pickup pauses one upgrade and resumes',()=>{const s=fresh();for(let n=0;n<3;n++)Object.assign(s.enemies[n],{active:true,kind:'walker',x:0,z:2.8+n*.35,hp:SURVIVOR_AK.damage,rewardDropped:false});s.player.yaw=0;for(let n=0;n<3;n++)s.fire();advance(s,.05);assert.equal(s.mode,'levelup');const frozen=s.time;advance(s,2);assert.equal(s.time,frozen);s.chooseUpgrade(s.upgradeChoices[0].id);assert.equal(s.mode,'playing');});
test('all upgrade cards modify stats',()=>{const fields={damage:'damage','fire-rate':'fireRate',movement:'movement','max-hp':'maxHp',pickup:'pickupRadius',crit:'critChance',range:'range',armor:'armor'} as const;for(const [id,field] of Object.entries(fields)){const s=fresh(),old=s.stats[field as keyof typeof s.stats];upgrade(s,id);assert.ok(s.stats[field as keyof typeof s.stats]>old,id);}});
test('level five opens support mutation',()=>{const s=fresh();s.gainXp(36+54+72+90);for(let n=0;n<4;n++)s.chooseUpgrade(s.upgradeChoices[0].id);assert.equal(s.weapon.id,'survivor-ak');s.chooseMutation('rpk');assert.equal(s.weapon.id,'rpk');assert.equal(s.runSummary.currentWeapon,'RPK');s.finishEvolution();assert.equal(s.mode,'playing');});
test('weapon branches behave differently',()=>{const support=fresh();support.weapon=HEAVY_GUNNER;Object.assign(support.enemies[0],{active:true,kind:'tank',x:0,z:5,hp:500});support.player.yaw=0;support.fire();assert.ok(support.enemies[0].hp<500);const shotgun=fresh();shotgun.weapon=HELLMAKER;Object.assign(shotgun.enemies[0],{active:true,kind:'tank',x:0,z:5,hp:500});shotgun.player.yaw=0;shotgun.fire();assert.ok(shotgun.weapon.projectileCount>1);const marksman=fresh();marksman.weapon=ANTI_MATERIEL;Object.assign(marksman.enemies[0],{active:true,kind:'tank',x:0,z:6,hp:500});marksman.player.yaw=0;marksman.fire();assert.ok(marksman.weapon.critBonus!>0);});
test('all branches evolve at levels 5, 10, 15',()=>{assert.deepEqual(EVOLUTION_LEVELS,[0,5,10,15]);for(const [branch,first] of [['support','rpk'],['shotgun','breacher'],['marksman','svd-hunter']] as const){const s=fresh();s.gainXp(Array.from({length:14},(_,i)=>xpThreshold(i+1)).reduce((a,b)=>a+b,0));for(let level=2;level<=15;level++){s.chooseUpgrade(s.upgradeChoices[0].id);if(level===5)s.chooseMutation(first);if([5,10,15].includes(level)){const stage=[5,10,15].indexOf(level);assert.equal(s.weapon,WEAPON_EVOLUTIONS[branch][stage]);assert.equal(s.weapon.branch,branch);s.finishEvolution();}}}});
test('ten debug slots are grounded weapons',()=>{assert.equal(DEBUG_WEAPONS.length,10);assert.deepEqual(DEBUG_WEAPONS.map(w=>w.id),['survivor-ak','rpk','m249-support','heavy-gunner','breacher','saiga-12','hellmaker','svd-hunter','battle-dmr','anti-materiel']);assert.ok(M249_SUPPORT.damage>RPK.damage);assert.ok(SAIGA_12.projectileCount>1);assert.ok(BATTLE_DMR.range>BREACHER.range);assert.equal(CONFIG.mutationLevel,5);});
